### ISSUE TITLE
MPI_Cart_create return argument should be a pointer

### ISSUE THREAD

**Issue by vbharadwaj-bk** [rookiehpc/rookiehpc.github.io#324]
On this page, https://rookiehpc.org/mpi/docs/mpi_cart_create/index.html, the MPI communicator returned should be a pointer type MPI_Comm*, not MPI_Comm. See the OpenMPI documentation: https://www.open-mpi.org/doc/v4.1/man3/MPI_Cart_create.3.php

**Comment by rookiehpc** [comment]
Hi @vbharadwaj-bk,

well spotted, thank you raising it!
